### PR TITLE
Add gitignore and delete ignored files from repository

### PR DESCRIPTION
**Pull request by muhrifqii**
I hoped it could help others to start contributing. Please review it

### CODE REVIEW

**Comment by mohammadalijf** [comment]
@muhrifqii thank you for your contribution. there are some issues in `.gitignore` file.
i think we need add Pods path in `.gitignore` file for Example folder too. otherwise pod install will generate all removed pod related files as untracked files.

```
# CocoaPods - Only use to conserve bandwidth / Save time on Pushing
#           - Also handy if you have a large number of dependant pods
#           - AS PER https://guides.cocoapods.org/using/using-cocoapods.html NEVER IGNORE THE LOCK FILE
Example/Pods/
```
also pod installation will modify `Example/UnderLineTextField-Example.xcodeproj/project.pbxproj`
which can be resolved by adding following below Xcode Patch

```
Example/*.xcodeproj/*
Example/!*.xcodeproj/project.pbxproj
Example/!*.xcodeproj/xcshareddata/
Example/!*.xcworkspace/contents.xcworkspacedata
```
also we need add these files to `.gitignore` file as well
```
### macOS ###
# General
.DS_Store
.AppleDouble
.LSOverride

# Icon must end with two \r
Icon

# Thumbnails
._*

# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

# Directories potentially created on remote AFP share
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk
```

**Comment by muhrifqii** [comment]
I missed that pod parts, thanks.

But the others, I don't think that is necessary on your project. But I think it's good to add them too.

Also, in my opinion, this part is not necessary
```
Example/*.xcodeproj/*
Example/!*.xcodeproj/project.pbxproj
Example/!*.xcodeproj/xcshareddata/
Example/!*.xcworkspace/contents.xcworkspacedata
```
Since `*.xcodeproj/*` has a wildcards on it's prefix, so `Example/` should be included as ignored files too.
And `!` means exclude

**Comment by mohammadalijf** [comment]
@muhrifqii 
`*.xcodeproj/*` means every file or path inside root folder with `xcodeproj` extension and every file inside that path

`**/*.xcodeproj/` means the same but for all subfolder too (recursive) but since we dont want mess around other xcodeprojects we should specify `Example` folder

**Comment by muhrifqii** [comment]
Woah you're right @mohammadalijf . Okay I get it

**Pull request merged**
